Repository netlify/gotrue-js, pull requests merged in 2020-06, with the labels that each got.

#83 fix: return a rejected promise when inner token is null or undefined
  src/user.js
Labels: type: bug

#85 ci: switch to GitHub actions
  .eslintrc.json
  .gitattributes
  .github/workflows/labeler.yml
  .github/workflows/node.yml
  .prettierrc
  .travis.yml
  package.json
  src/admin.js
  src/index.js
  src/user.js
  yarn.lock
Labels: type: chore

#87 chore: add renovate.json
  renovate.json
Labels: type: chore

#36 Added confirm parameter to documentation
  README.md
Labels: type: feature

#78 🏷️ Add return types
  .eslintrc.js
  .eslintrc.json
  index.d.ts
  package.json
  yarn.lock
Labels: type: bug

#97 chore(deps): update babel
  .babelrc
  .github/workflows/node.yml
  package.json
  yarn.lock
Labels: type: chore

#110 fix(docs): format readme file and add some missing arguments
  README.md
Labels: type: bug

#112 chore: add release command
  package.json
  release.config.js
  yarn.lock
Labels: type: chore

#113 chore: use cross-env in release command
  package.json
  yarn.lock
Labels: type: chore
